### ISSUE TITLE
Xanitizer plugin Error Message 

### ISSUE THREAD

**Issue by FXRS1963** [RIGS-IT/sonar-xanitizer#3] opened 2017-03-02 12:48 UTC
Hi all,
some days ago I installed SonarQube 5.6.6 based on Windows Server 2008.
After implementing different plugins I tried to get the xanitizer widget working to display findings on the dashboard. I scanned WebGoat files with the help of Xanitizer.exe successfully, kicked off manually to produce a report.
I followed the instructions given under sonar-xanitizer. Alas, SonarQube throws the following error message:

**ERROR web[rails] Can not render widget xanitizer: undefined method `created_at' for nil:NilClass**

I encounter similar error messages for OWASP dependency-check and zap plugin.

I think I got stuck somewhere in the general configuration.

Your thoughts and support is highly appreciated.

Regards FXRS

**Comment by normanwenzel** [comment] 2017-03-02 15:33
Hello FXRS,

I can not reproduce your problem with 5.6.6, so could you please give some more details?
- When does this error message occur? During the SonarQube analysis or when you are trying to add the widget?
- Are the Xanitizer findings collected, even if the widget does not work? You can check this on the Issues tab if you filter for tag "xanitizer".

Regards
Norman

**Comment by FXRS1963** [comment] 2017-03-13 12:37
Hoi Norman,

sorry for the delay responding to your answer.
The error occurs when adding the widget.
Filtering for tag xanitizer does not bring any results... Apparently, the findings are not collected so far.

Here is what I did:
1. Installation of Xanitizer 3.0.0
2. Installation of Xanitizer plugin which fits in the SonarQube version
3. Manual creation of a project "SonarQube Xanitizer Plugin"
4. Editing sonar-project.properties adding the following lines:
# Xanitizer Plugin Configuration
sonar.projectKey=sonar:xanitizer
sonar.projectName=SonarQube Xanitizer Plugin
sonar.projectVersion=1.0
sonar.sources=C:/Program Files/Xanitizer-3.0.0/reporting/Xanitizer-Findings-List.xml
sonar.sourceEncoding=UTF-8
5. Inserting the path C:/Program Files/Xanitizer-3.0.0/reporting/Xanitizer-Findings-List.xml
to SonarQube UI under "Administration --> General Settings --> Xanitizer --> XML Report File"
6. Widget Setup under "Dashboard" --> "Xanitizer Findings" --> Select project "SonarQube Xanitizer Plugin"
7. Manual starting Xanitizer scan on WebGoat example code
8. Checking "Xanitizer-Findings-List.XML" being created successfully - Yes, it's there...
8. Receive error message: "An error occurred while trying to display the widget "xanitizer". Please contact the administrator". when checking the dashboard.

Annotation: Xanitizer does nowhere show up in SonarQube other than in Quality Profiles with 1 project supplied with 49 rules and "SonarQube Xanitizer Plugin" flagged and the manually created dashboard.
Sonar-Runner and Sonar-Scanner installed...
Database: MySQL 5.7 with a schema "sonar" and a user "sonarqube" with full rights on it.

I have the same error message for ZAP scanner and Dependency Check plugin...

Maybe this helps to identify the problem. If there are any information missing, please let me know.

At this point thanks for your support

FXRS

**Comment by normanwenzel** [comment] 2017-03-20 10:08
Thanks for the detailed description.
First of all, it looks like your configuration is not correct:
sonar.sources should point to a directory containing the source code of your project (this has nothing to do with the Xanitizer plugin, it is a SonarQube property).Additionally,  I am not sure if the value of sonar.projectName may contain whitespaces - I would advice to remove them.

If you are analyzing WebGoat, you do not need to adapt the sonar.properties file / create a new file. Xanitizer already contains a correct sonar.properties file for it in <InstallDir>/examples/webgoat.

You can simply execute Sonar-Runner from inside this directory and should at least get the issues.

I have no idea if the problem with the widget is a side effect of the wrong configuration. Since you have the problem with other plugins too, maybe it is a bug in the used SonarQube version.
Widget support is removed in SonarQube 6, so the widget will vanish soon anyway.

**Comment by normanwenzel** [comment] 2017-09-01 06:56
FIXED in 1.4.0

**Closed by normanwenzel** 2017-09-01 06:56 UTC
